// initialize_vault.ts — idempotent vault initializer for the demo flow.
//
// Reads:
//   ANCHOR_WALLET            admin keypair (signs init)
//   AGENT_KEYPAIR_PATH       agent keypair (auto-generated by demo.sh)
//   USDC_MINT                devnet Circle USDC
//   WSOL_MINT                native wSOL (`So111…`)
//   PYTH_SOL_USD_FEED_ID_HEX optional; defaults to canonical SOL/USD id
//   HELIUS_RPC_URL           devnet RPC
//   SPECTRAQ_PROGRAM_ID      vault program id
//
// Behaviour:
//   - If the vault PDA already exists, prints the pubkeys and exits 0.
//   - Otherwise sends `initialize_vault`, then prints+appends to .env.demo:
//       VAULT_PUBKEY, SHARE_MINT_PUBKEY, USDC_VAULT_ATA, SOL_VAULT_ATA.

import * as fs from "node:fs";
import * as path from "node:path";

import * as anchor from "@coral-xyz/anchor";
import { Connection, Keypair, PublicKey } from "@solana/web3.js";
import { getAssociatedTokenAddressSync } from "@solana/spl-token";

const { AnchorProvider, Program, Wallet } = anchor;

const ROOT = path.resolve(__dirname, "..");

function loadEnv() {
  const envPath = path.join(ROOT, ".env");
  if (!fs.existsSync(envPath)) return;
  for (const line of fs.readFileSync(envPath, "utf8").split("\n")) {
    const m = line.match(/^([A-Z_][A-Z0-9_]*)\s*=\s*(.*)$/);
    if (!m) continue;
    if (process.env[m[1]] === undefined) {
      let v = m[2].trim();
      if (
        (v.startsWith('"') && v.endsWith('"')) ||
        (v.startsWith("'") && v.endsWith("'"))
      ) {
        v = v.slice(1, -1);
      }
      // resolve ${VAR} interpolation against current env
      v = v.replace(/\$\{([A-Z_][A-Z0-9_]*)\}/g, (_, k) => process.env[k] ?? "");
      process.env[m[1]] = v;
    }
  }
}

function loadKeypair(p: string): Keypair {
  const expanded = p.replace(/^~/, process.env.HOME ?? "");
  const data = JSON.parse(fs.readFileSync(expanded, "utf8"));
  return Keypair.fromSecretKey(Uint8Array.from(data));
}

function appendEnvDemo(entries: Record<string, string>) {
  const file = path.join(ROOT, ".env.demo");
  const existing = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : "";
  const map = new Map<string, string>();
  for (const line of existing.split("\n")) {
    const m = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
    if (m) map.set(m[1], m[2]);
  }
  for (const [k, v] of Object.entries(entries)) map.set(k, v);
  const out = [...map.entries()].map(([k, v]) => `${k}=${v}`).join("\n") + "\n";
  fs.writeFileSync(file, out);
}

const VAULT_SEED = Buffer.from("vault");
const SHARE_MINT_SEED = Buffer.from("share_mint");
const SOL_USD_FEED_ID_HEX_DEFAULT =
  "ef0d8b6fda2ceba41da15d4095d1da392a0d2f8ed0c6c7bc0f4cfac8c280b56d";

async function main() {
  loadEnv();

  const rpc = process.env.HELIUS_RPC_URL ?? "https://api.devnet.solana.com";
  const programId = new PublicKey(
    process.env.SPECTRAQ_PROGRAM_ID ??
      "96fHw6FzHUB8gAPPUUWRpyZuWo2NRPHJtJYcm7ERfugN",
  );
  const usdcMint = new PublicKey(
    process.env.USDC_MINT ?? "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU",
  );
  const solMint = new PublicKey(
    process.env.WSOL_MINT ?? "So11111111111111111111111111111111111111112",
  );
  const adminPath = process.env.ANCHOR_WALLET ?? `${process.env.HOME}/.config/solana/id.json`;
  const agentPath =
    process.env.AGENT_KEYPAIR_PATH ?? `${process.env.HOME}/.config/solana/agent.json`;

  const admin = loadKeypair(adminPath);
  const agent = loadKeypair(agentPath);

  if (admin.publicKey.equals(agent.publicKey)) {
    throw new Error("admin and agent keypairs must differ (program enforces this)");
  }

  const feedHex = process.env.PYTH_SOL_USD_FEED_ID_HEX ?? SOL_USD_FEED_ID_HEX_DEFAULT;
  const feedBytes = Buffer.from(feedHex, "hex");
  if (feedBytes.length !== 32) {
    throw new Error(`PYTH_SOL_USD_FEED_ID_HEX must be 32 bytes, got ${feedBytes.length}`);
  }

  const connection = new Connection(rpc, "confirmed");
  const provider = new AnchorProvider(connection, new Wallet(admin), {
    commitment: "confirmed",
  });
  anchor.setProvider(provider);

  const idlPath = path.join(ROOT, "target", "idl", "spectraq_vault.json");
  if (!fs.existsSync(idlPath)) {
    throw new Error(`Missing IDL at ${idlPath}; run \`anchor build\` first.`);
  }
  const idl = JSON.parse(fs.readFileSync(idlPath, "utf8"));
  // Anchor 0.32 expects `address` on the IDL header.
  if (!idl.address) idl.address = programId.toBase58();
  const program = new Program(idl, provider);

  const [vaultPda] = PublicKey.findProgramAddressSync(
    [VAULT_SEED, admin.publicKey.toBuffer()],
    programId,
  );
  const [shareMintPda] = PublicKey.findProgramAddressSync(
    [SHARE_MINT_SEED, vaultPda.toBuffer()],
    programId,
  );
  const usdcVaultAta = getAssociatedTokenAddressSync(usdcMint, vaultPda, true);
  const solVaultAta = getAssociatedTokenAddressSync(solMint, vaultPda, true);

  console.log("[init-vault] program          :", programId.toBase58());
  console.log("[init-vault] admin            :", admin.publicKey.toBase58());
  console.log("[init-vault] agent            :", agent.publicKey.toBase58());
  console.log("[init-vault] usdc_mint        :", usdcMint.toBase58());
  console.log("[init-vault] sol_mint  (wSOL) :", solMint.toBase58());
  console.log("[init-vault] vault_pda        :", vaultPda.toBase58());
  console.log("[init-vault] share_mint_pda   :", shareMintPda.toBase58());
  console.log("[init-vault] usdc_vault_ata   :", usdcVaultAta.toBase58());
  console.log("[init-vault] sol_vault_ata    :", solVaultAta.toBase58());

  const existing = await connection.getAccountInfo(vaultPda, "confirmed");
  if (existing) {
    console.log("[init-vault] vault PDA already exists — skipping initialize_vault.");
  } else {
    console.log("[init-vault] vault PDA does not exist — sending initialize_vault…");
    const sig = await (program.methods as any)
      .initializeVault([...feedBytes])
      .accounts({
        admin: admin.publicKey,
        agent: agent.publicKey,
        usdcMint,
        solMint,
      })
      .signers([admin])
      .rpc();
    console.log("[init-vault] tx:", sig);
    console.log(
      `[init-vault] explorer: https://explorer.solana.com/tx/${sig}?cluster=devnet`,
    );
  }

  appendEnvDemo({
    VAULT_PUBKEY: vaultPda.toBase58(),
    SHARE_MINT_PUBKEY: shareMintPda.toBase58(),
    USDC_VAULT_ATA: usdcVaultAta.toBase58(),
    SOL_VAULT_ATA: solVaultAta.toBase58(),
    AGENT_PUBKEY: agent.publicKey.toBase58(),
    ADMIN_PUBKEY: admin.publicKey.toBase58(),
  });
  console.log("[init-vault] wrote .env.demo");
}

main().catch((e) => {
  console.error("[init-vault] FAILED:", e);
  process.exit(1);
});
