// SpectraQ Vault — non-custodial trading vault on Solana.
//
// Mode 1 (live demo): pooled USDC + SOL deposits, SPL share-token accounting,
// agent-driven SOL/USDC trades on a moving-average crossover signal. USDT is
// out of scope for this build per the project owner's directive.
//
// Prompt 3 wires Arcium MPC: `request_signal_computation` queues an MPC job
// over an encrypted price window, the cluster threshold-decrypts the result,
// and `compute_ma_signal_callback` lands the plaintext signal back on chain.

use anchor_lang::prelude::*;
use arcium_anchor::prelude::*;

pub mod constants;
pub mod errors;
pub mod events;
pub mod instructions;
pub mod oracle;
pub mod state;

pub use constants::*;
pub use errors::{ErrorCode, VaultError};
pub use events::*;
pub use oracle::PRICE_BOUNDS_SOL_USD;
pub use state::*;

// Anchor's `#[program]` macro looks for `crate::__client_accounts_*` modules
// at crate root. Glob-export the submodules so those auto-generated
// `__client_accounts_*` modules surface here.
pub use instructions::callback_signal::*;
pub use instructions::deposit_sol::*;
pub use instructions::deposit_usdc::*;
pub use instructions::execute_trade::*;
pub use instructions::init_ma_signal_comp_def::*;
pub use instructions::initialize_vault::*;
pub use instructions::request_signal_computation::*;
pub use instructions::settle_pnl::*;
pub use instructions::withdraw::*;
#[cfg(feature = "mock-mpc")]
pub use instructions::mock_callback_signal::*;

declare_id!("96fHw6FzHUB8gAPPUUWRpyZuWo2NRPHJtJYcm7ERfugN");

/// Pre-computed comp-def offset for the `compute_ma_signal` circuit. Used by
/// `derive_comp_def_pda!` in both the queue-comp and callback contexts so
/// they reference the same on-chain ComputationDefinitionAccount.
pub const COMP_DEF_OFFSET_COMPUTE_MA_SIGNAL: u32 = comp_def_offset("compute_ma_signal");

#[arcium_program]
pub mod spectraq_vault {
    use super::*;

    pub fn initialize_vault(
        ctx: Context<InitializeVault>,
        sol_usd_feed_id: [u8; 32],
    ) -> Result<()> {
        instructions::initialize_vault::initialize_vault_handler(ctx, sol_usd_feed_id)
    }

    pub fn deposit_usdc(
        ctx: Context<DepositUsdc>,
        amount: u64,
        sol_usdc_price_e6: u64,
    ) -> Result<()> {
        instructions::deposit_usdc::deposit_usdc_handler(ctx, amount, sol_usdc_price_e6)
    }

    pub fn deposit_sol(
        ctx: Context<DepositSol>,
        amount_lamports: u64,
    ) -> Result<()> {
        instructions::deposit_sol::deposit_sol_handler(ctx, amount_lamports)
    }

    pub fn withdraw(ctx: Context<Withdraw>, shares_to_burn: u64) -> Result<()> {
        instructions::withdraw::withdraw_handler(ctx, shares_to_burn)
    }

    pub fn init_ma_signal_comp_def(ctx: Context<InitMaSignalCompDef>) -> Result<()> {
        instructions::init_ma_signal_comp_def::init_ma_signal_comp_def_handler(ctx)
    }

    pub fn request_signal_computation(
        ctx: Context<RequestSignalComputation>,
        computation_offset: u64,
        pubkey: [u8; 32],
        nonce_prices: u128,
        prices_ciphertexts: [[u8; 32]; 17],
        nonce_params: u128,
        params_ciphertexts: [[u8; 32]; 3],
    ) -> Result<()> {
        instructions::request_signal_computation::request_signal_computation_handler(
            ctx,
            computation_offset,
            pubkey,
            nonce_prices,
            prices_ciphertexts,
            nonce_params,
            params_ciphertexts,
        )
    }

    /// Real Arcium callback. Must live inside this module so that the
    /// `#[arcium_callback]` macro can inject the (private) `validate_callback_ixs`
    /// security check generated by `#[arcium_program]`.
    #[arcium_callback(encrypted_ix = "compute_ma_signal")]
    pub fn compute_ma_signal_callback(
        ctx: Context<ComputeMaSignalCallback>,
        output: SignedComputationOutputs<ComputeMaSignalOutput>,
    ) -> Result<()> {
        instructions::callback_signal::apply_signal(ctx, output)
    }

    /// Hackathon safety net — admin-only manual signal write. Compiled out
    /// of the binary unless the `mock-mpc` feature is enabled.
    #[cfg(feature = "mock-mpc")]
    pub fn mock_callback_signal(
        ctx: Context<MockCallbackSignal>,
        signal: i8,
    ) -> Result<()> {
        instructions::mock_callback_signal::mock_callback_signal_handler(ctx, signal)
    }

    pub fn execute_trade<'info>(
        ctx: Context<'_, '_, '_, 'info, ExecuteTrade<'info>>,
        direction: TradeDirection,
        amount: u64,
        min_amount_out: u64,
        jupiter_route_data: Vec<u8>,
        destination_ata_index: u8,
    ) -> Result<()> {
        instructions::execute_trade::execute_trade_handler(
            ctx,
            direction,
            amount,
            min_amount_out,
            jupiter_route_data,
            destination_ata_index,
        )
    }

    pub fn settle_pnl(ctx: Context<SettlePnl>) -> Result<()> {
        instructions::settle_pnl::settle_pnl_handler(ctx)
    }
}
